# Generated by Django 5.1.1 on 2024-10-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='favico-key.jpg', upload_to='photos/'),
        ),
    ]
